# Generated by Django 6.0.1 on 2026-01-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
